spring.profiles.active=local
spring.datasource.url=jdbc:mysql://localhost:3306/mailflow_db
spring.datasource.username=root
spring.datasource.password=Root@123

spring.mail.username=2005sanyagoyal@gmail.com
spring.mail.password=hknr tyoq dgjf dzey